<<<<<<< HEAD
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
=======
package org.example;
public class App {
    public static void main(String[] args) {
        Calculator calculator = new Calculator();
        
        int sum = calculator.add(10,5);
        int product = calculator.multiply(10, 5);
        int difference = calculator.subtract(10, 5);
        int quotient = calculator.divide(10 ,5);
        String reverse = calculator.reverseString("hello");

        System.out.println("Sum: " + sum);
        System.out.println("Product: " + product);
        System.out.println("Difference: " + difference);
        System.out.println("Quotient: " + quotient);
        System.out.println("Reversed String: " + reverse);
    }
}
>>>>>>> 9d19c19e109a899bd4dc6f82db5126ffc0e5aec1
