    /*
    * This source file was generated by the Gradle 'init' task
    */


    public class App {
        public static void main(String[] args) {
            Calculator calculator = new Calculator();
    
            int sum = calculator.addNumbers(10, 5);
            int product = calculator.multiplyNumbers(5, 5);
            int difference = calculator.subtractNumbers(62, 25);
            int quotient = calculator.safelyDivide(100, 25);
    
            System.out.println("Sum: " + sum);
            System.out.println("Product: " + product);
            System.out.println("Difference: " + difference);
            System.out.println("Quotient: " + quotient);
    }
}
    
