/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.commons.lang3.StringUtils;

public class App {

    public static String reverseString(String input) {
        return StringUtils.reverse(input);
    }
    public static void main(String[] args) {
        Calculator calculator = new Calculator();
        
        int sum = calculator.add(10, 5);
        int sub = calculator.subtract(10, 5);
        int prod = calculator.multiply(10, 5);
        double div = calculator.divide(10, 5);

        System.out.println("Sum: " + sum);
        System.out.println("Sub: " + sub);
        System.out.println("Prod: " + prod);
        System.out.println("Div: " + div);
        System.out.println(reverseString("hello"));
    }
}
